version: "3.8"

services: 

  frontend: 
    build: 
      context: ./frontend
      dockerfile: Dockerfile 
    container_name: frontend 

  api: 
    build: 
      context: ./api 
      dockerfile: Dockerfile
    container_name: api

  database: {}

  cached: {} 
  
       

    